# Polls routes
### Create a poll
POST http://localhost:3333/polls HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
  "title": "Qual o melhor framework Node.js?",
  "options": ["Express", "Fastify", "NestJS", "HapiJS"]
}

### Get a poll
GET http://localhost:3333/polls/{id} HTTP/1.1
Host: localhost:3333
Content-Type: application/json

### Vote in a poll
POST http://localhost:3333/polls/{id}/votes HTTP/1.1
Host: localhost:3333
Content-Type: application/json

{
  "pollOptionId": "pollOptionId"
}